In [33]:
import pandas as pd

In [34]:
import numpy as np

In [35]:
df=pd.read_excel("C:\\Users\\rcmlp.12\\Desktop\\pirep delay\\EFG-E75_delay_piprep_data.xlsx")

In [36]:
df

New_ata_code  MONTH_CODE  Pirep  Inte
0              23      201801     33     5
1              23      201802     47     9
2              23      201803     59    10
3              23      201804     61    17
4              23      201805     41     7
..            ...         ...    ...   ...
235            52      202108     77    28
236            52      202109     63    29
237            52      202110     58    14
238            52      202111     54    12
239            52      202112     64    23

[240 rows x 4 columns]

In [37]:
X=df.iloc[:,2:3]
y=df.iloc[:,3:4]
X


Pirep
0       33
1       47
2       59
3       61
4       41
..     ...
235     77
236     63
237     58
238     54
239     64

[240 rows x 1 columns]

In [38]:
y

Inte
0       5
1       9
2      10
3      17
4       7
..    ...
235    28
236    29
237    14
238    12
239    23

[240 rows x 1 columns]

In [39]:
from sklearn.tree import DecisionTreeClassifier


In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [44]:
classifier= DecisionTreeClassifier()


In [45]:
classifier.fit(X_train,y_train)


DecisionTreeClassifier()

In [48]:
classifier.predict(X_test)

array([ 6,  7, 73, 15,  9,  2, 12, 36, 29, 18, 30, 12,  3, 22, 17, 10, 23,
        9,  7, 30, 29,  7, 10, 21, 33,  7,  7, 29, 12, 12,  9,  9, 32, 10,
       54, 31,  4, 25, 23, 17, 12, 30,  9, 19, 10, 36, 12, 24, 34, 35,  6,
       18, 10, 14,  7,  7, 33,  4, 47,  3, 62, 12,  3, 36, 10, 34, 11, 31,
       29, 10,  6, 21,  6, 12,  8, 36,  3, 30, 10, 10], dtype=int64)

In [49]:
classifier.predict(X_train)

array([10, 37, 12,  7,  8,  3,  4, 12,  4, 15,  9,  3,  9, 36, 11, 22, 12,
       10,  4,  9, 27, 40, 10,  8, 33, 12,  9,  5, 10, 17, 20, 12, 30,  9,
        5, 88, 25, 15, 10,  8, 14, 34, 30, 24,  9, 10, 12,  3,  6, 30,  2,
        7,  7, 17,  7, 54,  6, 34, 24, 14, 24,  7, 36, 10, 34, 18,  9, 11,
       10, 24, 10,  4, 35, 12,  5, 21, 73,  6, 17,  8,  7, 14, 10, 35,  9,
        7,  6,  3, 27, 11, 30, 12,  7,  2, 32, 62, 31,  6, 10, 64,  7, 17,
       27, 14, 10, 12, 17, 39,  9, 12,  7,  4, 33, 34, 23, 19, 17,  4,  8,
       15, 24,  6,  8, 22, 22, 45, 10, 16, 12, 12, 10, 11, 23,  7, 10,  7,
        9, 10, 33,  8, 10, 10, 19, 18, 29, 48, 14, 35, 10,  4, 32, 23,  6,
        7, 47, 15,  7, 64,  8, 10], dtype=int64)

In [50]:
classifier.predict(y_test)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Inte
Feature names seen at fit time, yet now missing:
- Pirep

  warnings.warn(message, FutureWarning)


array([ 4,  4,  7,  2,  4,  4,  2,  7,  4, 10,  4,  2,  7,  4,  2,  2,  4,
        4,  4,  2,  4,  4, 14,  4,  4,  4,  4,  2,  4,  4,  2,  4,  4,  4,
        4,  9,  4,  5,  2,  4,  4,  2,  4,  4,  4,  9,  4,  4,  3,  2,  4,
        4,  4,  4,  4,  4,  2,  4,  9,  2, 21,  5,  8,  9,  2,  9,  2,  3,
        4,  4,  4,  2,  4,  4,  4,  2,  4,  2,  4,  4], dtype=int64)

In [51]:
classifier.predict(y_train)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Inte
Feature names seen at fit time, yet now missing:
- Pirep

  warnings.warn(message, FutureWarning)


array([ 4,  9,  2,  4, 30,  4,  4,  4,  4,  2,  4,  4,  4, 17, 10,  2,  4,
        4,  4,  4, 14, 14,  4,  2,  5,  4,  4,  4,  4,  4,  2, 14, 10,  4,
        4, 17,  2,  4,  4,  4,  4, 14, 12,  2,  4,  4,  4,  4,  4, 10,  4,
        4,  4,  7,  4, 12,  4, 14,  2,  4,  2,  4, 17,  4, 14,  4,  4,  4,
        4,  2,  4,  4,  3,  4,  4,  2, 10,  4,  4,  4,  4,  4,  4,  3,  4,
        2,  4,  4, 14,  4, 10,  4,  4,  4,  7, 19, 12,  2,  2, 23,  4,  4,
       14,  4,  2,  4,  4,  8,  4, 12,  4,  4,  5, 14,  2,  4,  4,  4,  4,
        4,  4,  4,  4, 14,  2,  6,  4,  4,  4,  4,  4,  4,  2,  4,  4,  4,
        4,  4,  5,  4,  2,  4,  4,  4,  4,  7,  4,  3,  5, 12,  7,  2,  4,
        4, 10,  4,  4, 23,  4,  2], dtype=int64)